CREATE TABLE permissions (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(400),
    slug VARCHAR(50),
    added_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY(id)
);

INSERT INTO permissions(id, description, slug)
VALUES
    (1, 'Allow user account create', 'account_create'),
    (2, 'Allow user account delete', 'account_delete'),
    (3, 'Allow user account create', 'auth_create'),
    (4, 'Allow user account create', 'auth_create');
