CREATE TABLE role_permissions (
    role_id INT GENERATED BY DEFAULT AS IDENTITY,
    permission_id INT NOT NULL,
    role_slug VARCHAR(50) NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY(role_id),
    CONSTRAINT fk_permissions FOREIGN KEY(permission_id) REFERENCES permissions(id)
);


INSERT INTO role_permissions(role_id, permission_id, role_slug)
VALUES  (1, 1, 'administrator');
