CREATE TABLE rubrics (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    section VARCHAR(50) NOT NULL,
    section_percentage SMALLINT
    criterion VARCHAR(50) NOT NULL,
    criterion_weight SMALLINT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY(id),
);

CREATE TABLE rubrics_score (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    rubrics_id INT NOT NULL,
    description VARCHAR(100),
    criterion_score SMALLINT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY(id),
    CONSTRAINT fk_rubrics FOREIGN_KEY(rubrics_id) REFERENCES rubrics(rubrics_id)
);


INSERT INTO rubrics(id, section, section_percentage, criterion, criterion_weight)
VALUES  (1, 'Report', 40, 'Organization And Format (Whole Report)', 1),
        (2, 'Report', 40, 'Proper Citations (Whole Report)', 1),
        (3, 'Report', 40, 'Writing and English Quality (Whole Report)', 3),
        (4, 'Report', 40, 'Size Of the Report (Whole Report)', 1),
        (5, 'Report', 40, 'Motivation For the Project (Chapter 1 – Introduction)', 3),


        (17, 'Cooperation with the supervisor', 10, 'Frequency of interaction with the instructor', 3),


        (20, 'Quality and contribution of the project', 10, 'Multi-disciplinary development', 2);


INSERT INTO rubrics_score(id, rubrics_id, description, criterion_score)
VALUES  (1, 1, 'Report follows the format specified for CMSE projects exactly', 4),
        (2, 1, 'Report leaves out 1-2 chapters of the format', 3),
        (3, 1, 'Report leaves out 3-4 chapters of the format', 2),
        (4, 1, 'Report leaves out more than 4 chapters of the format', 1),

        (5, 2, 'Every statement is either original or is properly cited. Cited material is only a small portion of the whole (less than 10%)', 4),
        (6, 2, 'Every statement is either original or is properly cited. Cited material is sizable portion of the whole (between 10 and 30%).', 3),
        (7, 2, 'Most of the statements are original, but there are some quotations that are not properly cited.', 2),
        (8, 2, 'Most of the report is copied from some source, without proper citation.', 1),

        (9, 3, 'No errors in sentence structure and word usage. No spelling mistakes.', 4),
        (10, 3, 'Almost no errors in sentence structure and word usage. Very few spelling mistakes.', 3),
        (11, 3, 'Many errors in sentence structure and word usage. Many spelling mistakes.', 2),
        (12, 3, 'Numerous and distracting errors in sentence structure and word usage.', 1),

        (13, 4, '>30 pages', 4),
        (14, 4, '20-29 pages', 3),
        (15, 4, '10-19 pages', 2),
        (16, 4, '<10 pages', 1),

        (17, 5, 'The motivation for the project, general background for the project, why it is needed are explained well.', 4),
        (18, 5, 'The motivation for the project, general background for the project, why it is needed are explained but some important aspects are left out.', 3),
        (19, 5, 'The motivation for the project, general background for the project, why it is needed are explained poorly.', 2),
        (20, 5, 'The motivation for the project, general background for the project, why it is needed are not explained at all.', 1),
