CREATE TABLE rubrics (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    section VARCHAR(50) NOT NULL,
    section_percentage SMALLINT,
    criterion VARCHAR(200) NOT NULL,
    criterion_weight SMALLINT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY(id)
);

CREATE TABLE rubrics_score (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    rubrics_id INT NOT NULL,
    description VARCHAR(500),
    criterion_score SMALLINT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY(id),
    CONSTRAINT fk_rubrics FOREIGN KEY(rubrics_id) REFERENCES rubrics(id)
);


INSERT INTO rubrics(id, section, section_percentage, criterion, criterion_weight)
VALUES  (1, 'Report', 40, 'Organization And Format (Whole Report)', 1),
        (2, 'Report', 40, 'Proper Citations (Whole Report)', 1),
        (3, 'Report', 40, 'Writing and English Quality (Whole Report)', 3),
        (4, 'Report', 40, 'Size Of the Report (Whole Report)', 1),
        (5, 'Report', 40, 'Motivation For the Project (Chapter 1 – Introduction)', 3),
        (6, 'Report', 40, 'Project Planning and Management (chapter 2)', 2),
        (7, 'Report', 40, 'Requirements Analysis (Chapter 3, sections 3.1 and 3.2)', 4),
        (8, 'Report', 40, 'Realistic Constraints (Chapter 3, section 3.3)', 2),
        (9, 'Report', 40, 'Ethical issues (Chapter 3, section 3.4)', 1),
        (10, 'Report', 40, 'System design  (chapter 4)', 5),
        (11, 'Report', 40, 'Implementation (chapter 5, sections 5.1,  5.2, 5.4)', 6),
        (12, 'Report', 40, 'Standards (chapter 5, section 5.3)', 1),
        (13, 'Report', 40, 'Quality Assurance & Quality Control Testing (chapter 6)', 4),
        (14, 'Report', 40, 'User guide for the system (chapter 7)', 2),
        (15, 'Report', 40, 'Description of the solution’s impact in the global, economic, environmental and societal context. (chapter 8- discussion)', 2),
        (16, 'Report', 40, 'References', 1),
        (17, 'Report', 40, 'Appendices', 1),


        (18, 'Cooperation with the supervisor', 10, 'Frequency of interaction with the instructor', 3),
        (19, 'Cooperation with the supervisor', 10, 'Progress reports', 3),
        (20, 'Cooperation with the supervisor', 10, 'Project developed with full cooperation of the supervisor', 4),


        (21, 'Quality and contribution of the project', 30, 'Multi-disciplinary development', 2),
        (22, 'Quality and contribution of the project', 30, 'Contribution of new ideas', 6),
        (23, 'Quality and contribution of the project', 30, 'Implementation quality', 10),
        (24, 'Quality and contribution of the project', 30, 'Use of modern implementation tools', 4),
        (25, 'Quality and contribution of the project', 30, 'Project solves a realistic problem', 8),

        (26, 'Presentation', 20, 'Organization', 2),
        (27, 'Presentation', 20, 'Time usage', 2),
        (28, 'Presentation', 20, 'Quality and relevance of the slides', 4),
        (29, 'Presentation', 20, 'Communication Skills', 4),
        (30, 'Presentation', 20, 'Questions and Answers', 8);


INSERT INTO rubrics_score(id, rubrics_id, description, criterion_score)
VALUES  (1, 1, 'Report follows the format specified for CMSE projects exactly', 4),
        (2, 1, 'Report leaves out 1-2 chapters of the format', 3),
        (3, 1, 'Report leaves out 3-4 chapters of the format', 2),
        (4, 1, 'Report leaves out more than 4 chapters of the format', 1),

        (5, 2, 'Every statement is either original or is properly cited. Cited material is only a small portion of the whole (less than 10%)', 4),
        (6, 2, 'Every statement is either original or is properly cited. Cited material is sizable portion of the whole (between 10 and 30%).', 3),
        (7, 2, 'Most of the statements are original, but there are some quotations that are not properly cited.', 2),
        (8, 2, 'Most of the report is copied from some source, without proper citation.', 1),

        (9, 3, 'No errors in sentence structure and word usage. No spelling mistakes.', 4),
        (10, 3, 'Almost no errors in sentence structure and word usage. Very few spelling mistakes.', 3),
        (11, 3, 'Many errors in sentence structure and word usage. Many spelling mistakes.', 2),
        (12, 3, 'Numerous and distracting errors in sentence structure and word usage.', 1),

        (13, 4, '>30 pages', 4),
        (14, 4, '20-29 pages', 3),
        (15, 4, '10-19 pages', 2),
        (16, 4, '<10 pages', 1),

        (17, 5, 'The motivation for the project, general background for the project, why it is needed are explained well.', 4),
        (18, 5, 'The motivation for the project, general background for the project, why it is needed are explained but some important aspects are left out.', 3),
        (19, 5, 'The motivation for the project, general background for the project, why it is needed are explained poorly.', 2),
        (20, 5, 'The motivation for the project, general background for the project, why it is needed are not explained at all.', 1),

        (21, 6, '13-16 of the items on the Project Planning & Management Checklist have been done.', 4),
        (22, 6, '9-12 of the items on the Project Planning & Management Checklist have been done.', 3),
        (23, 6, '5-8 of the items on the Project Planning & Management Checklist have been done.', 2),
        (24, 6, 'Less than 5 items on the Project Planning & Management Checklist have been done.', 1),

        (25, 8, 'Economic, environmental, social, political, ethical, health and safety, manufacturability, and sustainability constraints that the solution must satisfy are identified', 4),
        (26, 8, 'Most of the economic, environmental, social, political, ethical, health and safety, manufacturability, and sustainability constraints that the solution must satisfy are identified', 3),
        (27, 8, 'Only a few of the economic, environmental, social, political, ethical, health and safety, manufacturability, and sustainability constraints that the solution must satisfy are identified', 2),
        (28, 8, 'None of the economic, environmental, social, political, ethical, health and safety, manufacturability, and sustainability constraints that the solution must satisfy are identified', 1),

        (29, 9, 'All ethical issues relevant to the project have been discussed, including effect on the environment, effect in case system fails to function properly, effects on privacy, impact on employment, possibility of crime (hacking and data theft), protection against malware (viruses etc.), usage of pirated software', 4),
        (30, 9, 'Most ethical issues relevant to the project have been discussed', 3),
        (31, 9, 'Some ethical issues relevant to the project have been discussed', 2),
        (32, 9, 'No discussion of ethical issues', 1),

        (33, 10, 'Both high level and low-level system design (overall architecture, database design in the form of E-R diagrams, Relational Tables, Physical DB Tables, and UML diagrams (e.g. Sequence, Class diagrams, Associations of classes, Context diagrams, Entity-class diagrams for static modelling. State transition diagrams, Communication and/or Sequence diagrams for dynamic modelling, etc.)) are shown in sufficient detail and clarity in the report.', 4),
        (34, 10, 'Both high level and low-level system design (overall architecture, database design in the form of E-R diagrams, Relational Tables, Physical DB Tables, and UML diagrams (e.g. Sequence, Class diagrams, Associations of classes, Context diagrams, Entity-class diagrams for static modelling. State transition diagrams, Communication and/or Sequence diagrams for dynamic modelling, etc.)) are shown, but in not enough detail and clarity in the report.', 3),
        (35, 10, 'Although system design is shown in the report, it is not informative at all.', 2),
        (36, 10, 'No System design is shown in the report.', 1),

        (37, 11, 'Tools, technologies, and platforms used, algorithms developed, as well as the details of the implementation have been described thoroughly and clearly. ', 4),
        (38, 11, 'Tools, technologies, and platforms used, algorithms developed, as well as the details of the implementation have been described at a reasonable level. ', 3),
        (39, 11, 'Tools, technologies, and platforms used, algorithms developed, as well as the details of the implementation have been poorly described. ', 2),
        (40, 11, 'Tools, technologies, and platforms used, algorithms developed, as well as the details of the implementation have not been described at all. ', 1),

        (41, 12, 'There is a discussion of the relevant standards and the degree to which they have been used. ', 4),
        (42, 12, 'Relevant standards are stated, but their utilization is not discussed. ', 3),
        (43, 12, 'Standards that are not truly applicable to the project have been mentioned. ', 2),
        (44, 12, 'There is no mention of standards at all. ', 1),

        (45, 13, 'Includes strategies applied for Quality Assurance & Quality Control activities such as Quality Checks, Audits and Inspections done, Statistical Process Controls Charts, Fishbone diagrams, Test Cases Developed, Test Data Employed, Results of the Testing, as well as corrective actions taken considering these test and inspection results. It is clear that the solution has undergone extensive quality assurance and the necessary tests have been carried out.', 4),
        (46, 13, 'Includes strategies applied for Quality Assurance & Quality Control activities such as Quality Checks, Audits and Inspections done, Statistical Process Controls Charts, Fishbone diagrams, Test Cases Developed, Test Data Employed, Results of the Testing, as well as corrective actions taken considering these test and inspection results. Somewhat incomplete testing of the solution is evident.', 3),
        (47, 13, 'Some testing has been performed, but not enough to permit its use without reservations.', 2),
        (48, 13, 'No testing has been performed, and no results are reported.', 1),

        (49, 14, 'The system with all its functionality is explained clearly and in sufficient detail', 4),
        (50, 14, 'The system with all its functionality is explained, but some explanations are unclear or not in enough detail ', 3),
        (51, 14, 'Only part of system’s functionality is explained, and some are unclear or not in enough detail', 2),
        (52, 14, 'No useful explanation of the system’s functionality is present', 1),

        (53, 15, 'The solution’s impact in the global, economic, environmental, and societal context are analysed and explained thoroughly', 4),
        (54, 15, 'Most of the solution’s impact in the global, economic, environmental, and societal context are analysed and explained ', 3),
        (55, 15, 'Only some of the solution’s impact in the global, economic, environmental, and societal context are analysed and explained', 2),
        (56, 15, 'None of the solution’s impact in the global, economic, environmental, and societal context are analysed and explained', 1),

        (57, 16, 'Includes more than 10 major references ', 4),
        (58, 16, 'Includes 5-10 major references.', 3),
        (59, 16, 'Includes 3-4 major references.', 2),
        (60, 16, 'Includes less than 3 major references.', 1),

        (61, 17, 'Report has at least appendices A and B, Appendix A clearly explains the instructions for installing the system, and appendix B contains all the significant code', 4),
        (62, 17, 'Report has at least appendices A and B, Appendix A poorly explains the instructions for installing the system, or appendix B contains only some of the significant code', 3),
        (63, 17, 'Report leaves out one of appendices A or B.', 2),
        (64, 17, 'Report has no appendices', 1);

        (65, 18, 'Student visited his supervisor 8 or more times ', 4),
        (66, 18, 'Student visited his supervisor 6-7 times ', 3),
        (67, 18, 'Student visited his supervisor 4-5 times ', 2),
        (68, 18, 'Student visited his supervisor less than 4 times', 1),

        (69, 19, 'Student presented 4 or more progress reports', 4),
        (70, 19, 'Student presented 3 progress reports', 3),
        (71, 19, 'Student presented 2 progress reports', 2),
        (72, 19, 'Student presented one or no progress report', 1),

        (73, 20, 'Project was developed with full supervisor involvement at each step.', 4),
        (74, 20, 'Project developed with supervisor involvement only at major milestones.', 3),
        (75, 20, 'Project developed with minimal supervisor involvement.', 2),
        (76, 20, 'Project developed with no supervisor involvement except the initial determination of the project topic.', 1),

        (77, 21, 'The project was designed/implemented by a team of people from different disciplines and included at least one person outside of engineering', 4),
        (78, 21, 'Project was designed/implemented by at least one computer/software engineer and a person from another engineering field', 3),
        (79, 21, 'Project was designed/implemented by at least one software engineer and one computer engineer', 2),
        (80, 21, 'Project was designed/implemented by person(s) from the computer/software engineering discipline (only one discipline involved)', 1),

        (81, 22, 'Project contains many new and innovative ideas.', 4),
        (82, 22, 'Project contains some new and innovative ideas.', 3),
        (83, 22, 'Project contains few new and innovative ideas.', 2),
        (84, 22, 'Project contains no new ideas and innovative ideas.', 1),

        (85, 23, 'Project has a solid, robust implementation. It is designed and implemented using well-established engineering principles, and can handle all conceivable error conditions.', 4),
        (86, 23, 'Project has an acceptable implementation that works under normal circumstances but cannot handle all error conditions.', 3),
        (87, 23, 'Project has an acceptable implementation that works under normal circumstances but cannot handle most error conditions.', 2),
        (88, 23, 'Project has a shaky implementation that hardly works correctly. ', 1),

        (89, 24, 'State of the art engineering tools and techniques have been used in the design and implementation of the project (languages, frameworks, hardware etc.)', 4),
        (90, 24, 'Current, widely used engineering tools and techniques have been used in the design and implementation of the project. ', 3),
        (91, 24, 'Engineering tools and techniques that are still used but have been superseded by more up-to-date ones and are about to be retired have been used in the design and implementation of the project.', 2),
        (92, 24, 'Outdated, no longer current engineering tools and techniques have been used in the design and implementation of the project.', 1),

        (93, 25, 'Project solves a real/significant problem and can be used without modification.', 4),
        (94, 25, 'Project solves a simplified version of a real/significant problem but can easily be extended to solve the real-life problem.', 3),
        (95, 25, 'Project solves a vastly simplified version of a real/significant problem and requires major modification before it can be used to solve the real-life problem.', 2),
        (96, 25, 'Project solves a toy problem, without any real-life application.', 1),

        (97, 26, 'The topic was introduced clearly and creatively. Focus was maintained on the topic and the contribution was highlighted. The conclusion was logical, effective, and relevant.', 4),
        (98, 26, 'The topic was introduced clearly. Focus was maintained and the contribution was highlighted.The conclusion was satisfactory.', 3),
        (99, 26, 'The topic was not clearly introduced. The contribution was not obvious. Focus on the topic was not steady. There was a conclusion.', 2),
        (100, 26, 'The topic was not clearly introduced. Focus was not maintained on the topic. The contribution was not clear. There was no conclusion.', 1),

        (101, 27, 'All parts of the presentation were finished, where each part received enough time relative to its importance.', 4),
        (102, 27, 'All parts of the presentation were finished, but time allocated to each part was somewhat disproportionate to its significance.', 3),
        (103, 27, 'All parts of the presentation were finished, but time allocated to each part was largely disproportionate to its significance.', 2),
        (104, 27, 'Major part of the presentation was not finished.', 1),

        (105, 28, 'Slides were high quality, informative, attractive and contained useful graphics.', 4),
        (106, 28, 'Slides were of standard quality, and sufficiently informative.', 3),
        (107, 28, 'Slides were of low quality, and less than fully informative.', 2),
        (108, 28, 'Slides were totally unattractive and not informative at all.', 1),

        (109, 29, 'The project was presented in an enthusiastic, clearly understandable manner; listener interest in the topic was aroused and maintained.', 4),
        (110, 29, 'The project was presented in a reasonable way, with some attention being paid to how it was received.', 3),
        (111, 29, 'The project was presented in a dull and boring way, without any enthusiasm.', 2),
        (112, 29, 'Presentation was almost incomprehensible and/or uninteresting.', 1),

        (113, 30, 'The student demonstrated extensive knowledge of the topic by responding confidently, precisely and appropriately to all audience questions and feedback.', 4),
        (114, 30, 'The student demonstrated knowledge of the topic by responding accurately and appropriately to questions and feedback.', 3),
        (115, 30, 'The student demonstrated some knowledge of the topic by responding accurately and appropriately to questions and feedback.', 2),
        (116, 30, 'The student demonstrated incomplete knowledge of the topic by responding inaccurately and inappropriately to questions and feedback.', 1);

