CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    slug VARCHAR(50) NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY(id)
);

CREATE TABLE role_permissions (
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY(role_id, permission_id),
    CONSTRAINT fk_roles FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_permissions FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

INSERT INTO roles(slug)
VALUES
    ('administrator'),
    ('supervisor'),
    ('committee_member'),
    ('student');

INSERT INTO role_permissions(role_id, permission_id)
VALUES
    (1, 1),
    (2, 1),
    (3, 1),
    (4, 1),
    (1, 2),
    (2, 2),
    (3, 2),
    (4, 2),
    (1, 3),
    (2, 3),
    (3, 3),
    (4, 3),
    (1, 4),
    (2, 4),
    (3, 4),
    (4, 4);
